### ISSUE TITLE
Cannot find module 'electron-ipc-plus'

### ISSUE THREAD

**Issue by angryhorse0905** [electron-utils/electron-ipc-plus#1]
I am trying to use this module in custom protocol.
I call interceptBufferProtocol('file', .....) and in this function, I send event to renderer, and render has exactly same code from this guide.

But in Chrome DevTools Console says as following even I have synced all dependencies as same as this package.
-----
Cannot find module 'electron-ipc-plus'
-----

Please help me what's wrong asap.
Thanks

**Comment by jwu** [comment]
hi @angryhorse0905 

Can you send me a demo for this problem?
