### ISSUE TITLE
How can I 'unsubscribe' a listener?

### ISSUE THREAD

**Issue by nykma** [electron-utils/electron-ipc-plus#3]
Seems like `ipcPlusM.removeListener` is undefined, and `ipcPlusM` is not a valid `EventListener` implement (which means I cannot handle it using rxjs: `Invalid event target` is reported). 

So, How can I do the `removeListener` job?

**Comment by jwu** [comment]
Hi @nykma , thank you for your advice I just add it.

**Comment by jwu** [comment]
https://github.com/electron-utils/electron-ipc-plus/commit/263cfc8881bc4bc320b323c32165c2b48e4daaa1
